### Numpy Library
Processing N-Dimensional arrays

In [1]:
import numpy as np

li = [1,2,3, 'z']

a = np.array(li)

b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [2]:
m3 = np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]

1

In [6]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes

324

In [7]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
c = b.reshape(5,3)

In [9]:
c


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
d = c + 1
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [11]:
import numpy as np
M = np.ones((3, 3))
print("Matrix M:\n",M)

Matrix M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Pandas
Use Cases

- Data Cleaning
- Data Transformation
- Data Analysis
### Notations

- Series
- DataFrames

In [13]:
import pandas as pd


internal1 = {'s1':21, 's2':18, 's3':24}

internal1 = pd.Series(internal1)

internal2 = {'s1':15, 's2':18, 's3':12}
internal2 = pd.Series(internal2)
internal2

s1    15
s2    18
s3    12
dtype: int64

In [14]:
final = {'Internal1':internal1, 'Internal2':internal2}

final = pd.DataFrame(final)
final['Internal1']

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [15]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [16]:
final.columns # Names of all columns

Index(['Internal1', 'Internal2'], dtype='object')

In [17]:
final.values # Lists of all rows

array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [18]:
final.values[2]

array([24, 12], dtype=int64)

In [19]:
final.values[2,0] = 25
final.values[2][0]

25

In [20]:
for row in final.values:
    print('Internal1 - ',row[0],', Internal2 - ',row[1])

Internal1 -  21 , Internal2 -  15
Internal1 -  18 , Internal2 -  18
Internal1 -  25 , Internal2 -  12


In [21]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         25         12

In [22]:
final.loc['s4'] = [20, 18]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         25         12
s4         20         18

In [24]:
final.drop(3)

KeyError: '[3] not found in axis'